application: s~kellerberrin-drugdatabase
version: 1
runtime: python27
api_version: 1
threadsafe: true

builtins:
- remote_api: on

handlers:
    
- url: /html
  static_dir: html
  
- url: .*
  script: app.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest  