application: kellerberrin-doc
version: 1
runtime: python27
api_version: 1

threadsafe: no

builtins:
- remote_api: on

handlers:

- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico

- url: /html/software
  static_dir: html/software
  login: admin
  secure: always  
  auth_fail_action: redirect
  
- url: /html
  static_dir: html
  secure: always

- url: /.*
  script: gae_sphinx.py
  secure: always
 
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest  