#!/bin/bash
# Run a local version of the UVIS Sphinx documentation on
# the local Google App Engine server.

python $GOOGLEAPPBIN/dev_appserver.py \
  --port=$UVISSPHINXLOCALPORT  \
  --host=$UVISSPHINXLOCALHOST  \
  --storage_path=$UVISSPHINXLOCALSTORAGE \
  --admin_port=$UVISSPHINXADMINPORT \
  $UVISSPHINXGAEAPPPATH
