#!/bin/bash
# The uploader batch file.
# The the db_filename file checkpoints and restarts the batch upload after a 
# problem with a large upload. Delete this db file when the upload is complete.
# The local URL ("http://localhost:9080") must match the URL assigned to the
# local US Drug Database application. 

echo "UVISUSDRUGDATAPATH:" $UVISUSDRUGDATAPATH
echo "UVISUSDRUGDATAUPLOADFILE:" $UVISUSDRUGDATAUPLOADFILE
echo "UVISUSDRUGDATASTOREKIND:" $UVISUSDRUGDATASTOREKIND
echo "UVISUSDRUGDATALOCALURL:" $UVISUSDRUGDATALOCALURL
echo "UVISUSDRUGDATALOCALCHECKPOINT:" $UVISUSDRUGDATALOCALCHECKPOINT
echo "UVISDEVEMAILACCOUNT:" $UVISDEVEMAILACCOUNT

python $GOOGLEAPPBIN/appcfg.py upload_data --config_file=$UVISUSDRUGDATAPATH  --filename=$UVISUSDRUGDATAUPLOADFILE --kind=$UVISUSDRUGDATASTOREKIND --url=$UVISUSDRUGDATALOCALURL --db_filename=$UVISUSDRUGDATALOCALCHECKPOINT --email=$UVISDEVEMAILACCOUNT
