#!/bin/bash
# The batch file to rollback and unsuccessful software release.
# This rolls back the Authenticate web application
# 

echo "UVISAUTHENTICATEGAE:" $UVISAUTHENTICATEGAE
echo "UVISDEVEMAILACCOUNT:" $UVISDEVEMAILACCOUNT

python $GOOGLEAPPBIN/appcfg.py --verbose --email=$UVISDEVEMAILACCOUNT rollback $UVISAUTHENTICATEGAE
