#!/bin/bash
# The batch file to rollback and unsuccessful software release.
# This rolls back the PharmCat web application
# 

echo "UVISPHARMCATGAE:" $UVISPHARMCATGAE
echo "UVISDEVEMAILACCOUNT:" $UVISDEVEMAILACCOUNT

python $GOOGLEAPPBIN/appcfg.py --verbose --email=$UVISDEVEMAILACCOUNT rollback $UVISPHARMCATGAE
