#!/bin/bash
# Bash Makefile for UVIS Sphinx documentation
#
#


if [ -z "$SPHINXBUILD" ] 
then

	if [ -z "$SPHINXBIN" ]
	then
	
		echo ""
		echo "The 'sphinx-build.py' python command was not found. Make sure you have Sphinx"
		echo "installed, then set the SPHINXBUILD environment variable to point"
		echo "to the full path of the 'sphinx-build.py' python command." 
                echo "Alternatively you may define the environment variable SPHINXBIN to point to the top level" 
		echo "of the Sphinx Directory."
		echo "This can be done by executing 'go UVIS' this will create a bash shell"
                echo "with the correct environment."
		echo "If you don't have Sphinx installed, get it from 'http://sphinx-doc.org/'"

		exit 1	
	
	fi 

	SPHINXBUILD=$SPHINXBIN/sphinx-build

fi

if [ -z "$UVISSPHINX" ] 
then

	if [ -z "$UVISDIR" ]
	then
	
		echo ""
		echo "The UVIS Directory environment variable 'UVISDIR' is not defined"
		echo "define the environment variable by executing 'go UVIS'"
		echo "this will create a bash shell with the correct environment"

		exit 1	
	
	fi 

	UVISSPHINX=$UVISDIR/Sphinx

fi


if [ -z "$BUILDDIR" ] 
then

     BUILDDIR="$UVISSPHINX/SphinxGAE"

fi

if [ -z "$SOURCEDIR" ] 
then

     SOURCEDIR="$UVISSPHINX/Source"

fi

if [ ! -z "$PAPER" ]
then

     ALLSPHINXOPTS="-D latex_paper_size=$PAPER $ALLSPHINXOPTS"

fi


if [ -z "$1" ] || [ "$1" = "help" ]
then

	echo "Please execute use sphinxmake <target> where <target> is one of"
	echo "html       to make standalone HTML files"
	echo "dirhtml    to make HTML files named index.html in directories"
	echo "singlehtml to make a single large HTML file"
	echo "pickle     to make pickle files"
	echo "json       to make JSON files"
	echo "htmlhelp   to make HTML files and a HTML help project"
	echo "qthelp     to make HTML files and a qthelp project"
	echo "devhelp    to make HTML files and a Devhelp project"
	echo "epub       to make an epub"
	echo "latex      to make LaTeX files, you can set PAPER=a4 or PAPER=letter"
	echo "text       to make text files"
	echo "man        to make manual pages"
	echo "texinfo    to make Texinfo files"
	echo "gettext    to make PO message catalogs"
	echo "changes    to make an overview over all changed/added/deprecated items"
	echo "xml        to make Docutils-native XML files"
	echo "pseudoxml  to make pseudoxml-XML files for display purposes"
	echo "linkcheck  to check all external links for integrity"
	echo "doctest    to run all doctests embedded in the documentation if enabled"
	
	exit 0

fi

ALLSPHINXOPTS="-d $BUILDDIR/doctrees $SPHINXOPTS $SOURCEDIR"

python $SPHINXBUILD -M $1 $ALLSPHINXOPTS $BUILDDIR/$1

if [ ! -n $? ]
then
	echo ""
	echo "Sphinx Build Failed. Status Code:" $?
	echo ""
	exit $?	
fi
	
echo ""
echo "Build Successful. The documentation pages are in:" $BUILDDIR/$1
exit 0
