#!/bin/bash
# The uploader batch file.
# This uploads the local US Drug Database application to the 
# Google Application Engine

echo "UVISUSDRUGGAE:" $UVISUSDRUGGAE
echo "UVISDEVEMAILACCOUNT:" $UVISDEVEMAILACCOUNT

python $GOOGLEAPPBIN/appcfg.py --verbose --email=$UVISDEVEMAILACCOUNT update $UVISUSDRUGGAE
