#!/bin/bash
# The uploader batch file.
# This uploads the local PharmCat web application to the 
# Google Application Engine

echo "UVISPHARMCATGAE:" $UVISPHARMCATGAE
echo "UVISDEVEMAILACCOUNT:" $UVISDEVEMAILACCOUNT

python $GOOGLEAPPBIN/appcfg.py --verbose --email=$UVISDEVEMAILACCOUNT update $UVISPHARMCATGAE
