#!/bin/bash
# Define the environment variables for the
# US drug application.
# Should be run once in each terminal session
# when working on UVIS US drug software.
# It is run autmatically by the 'workenv UVIS' script  


#US Drug Database
#The US Drug Database GAE application name (defined in app.yaml)
export UVISUSDRUGGAEAPPNAME="s~kellerberrin-drugdatabase"
#The directory for the US Drug Database Google App Engine files (app.yaml is here)
export UVISUSDRUGGAE="$UVISDIR/GAEServer/NDCWeb"
#The directory and name for the US Drug Database Google Application (app name is defined in app.yaml)
export UVISUSDRUGGAEAPPPATH="$UVISUSDRUGGAE/app.yaml"
#The local URL for the US Drug database
export UVISUSDRUGLOCALHOST="localhost"
#The local port for the US Drug Database.
export UVISUSDRUGLOCALPORT="9080"
#The local admin port for the US Drug Database 
export UVISUSDRUGADMINPORT="8040"
#Local storage (logs & datastore) for the US DrugDatabase
export UVISUSDRUGLOCALSTORAGE="$UVISGAELOCALSTORAGE/USDrugDatabase" 
#The remote URL for the US Drug Database.
export UVISUSDRUGURL="http://kellerberrin-drugdatabase.appspot.com"
#
# Documentation for the US Drug Database bulkuploader
#
# The US Drug Database Datastore Kind (equivalent to an SQL table)
# This must be equal to the name of the Kind defined in the Python application code.
export UVISUSDRUGDATASTOREKIND="NDCLookup"
# The directory for the USDrug Database Data files (bulkloader.yaml is here)
export UVISUSDRUGDATA="$UVISDIR/GAEServer/NDCDatafilesUpload"
#The path for the USDrug Database Data files (specifies bulkloader.yaml)
export UVISUSDRUGDATAPATH="$UVISUSDRUGDATA/bulkloader.yaml"
#The FULL (100,000 records+Images) USDrug Database Data .csv file to be uploaded.
export UVISUSDRUGDATAUPLOADFILE="$UVISUSDRUGDATA/csvupload/NDCImageDatabase.csv"
#The USDrug LOCAL Datastore URL.
export UVISUSDRUGDATALOCALURL="http://${UVISUSDRUGLOCALHOST}:${UVISUSDRUGLOCALPORT}/_ah/remote_api"
#The USDrug REMOTE Datastore URL.
export UVISUSDRUGDATAREMOTEURL="$UVISUSDRUGURL/_ah/remote_api"
#The uploader checkpoint database. Used for re-starting the upload. 
export UVISUSDRUGDATALOCALCHECKPOINT="$UVISUSDRUGDATA/csvupload/bulkloader-local-upload-progress.sql3"
#The uploader checkpoint database. Used for re-starting the upload. 
export UVISUSDRUGDATAREMOTECHECKPOINT="$UVISUSDRUGDATA/csvupload/bulkloader-remote-upload-progress.sql3"


# Raw US Drug Data Processing. See kellerberrin-doc.appspot.com for further details.
# These environment variables are used by Python software that converts the files downloaded 
# from the US Food & Drug Administration (FDA) website to .csv files that can be uploaded 
# into the GAE datastore using the bulkloader software after being annotated with image information.

# The directory for the raw NDC data files 
export UVISUSDRUGRAWNDCDIR="$UVISDATADIR/RawNDCDataFiles"
# The raw product text file. This file is tab delimited between records (1 record per line).
export UVISUSDRUGRAWDATAPRODUCT="$UVISUSDRUGRAWNDCDIR/product.txt"
# The raw package file. This file is tab delimited between records (1 record per line).
export UVISUSDRUGRAWDATAPACKAGE="$UVISUSDRUGRAWNDCDIR/package.txt"
# The raw data python log file.
export UVISUSDRUGRAWDATALOGFILE="$UVISUSDRUGDATA/csvupload/processrawNDCfiles.log"
#If set to the FULL file then uploads all the data (100,000 records)
export UVISUSDRUGDATAFILE="$UVISUSDRUGDATA/csvupload/NDCDatabase.csv"


# The main directory for files and logs of the National LIbrary of Medicine RxImage download.

export UVISUSDRUGIMAGEDIR="$UVISUSDRUGDATA"
# The image download python log file.
export UVISUSDRUGIMAGELOGFILE="$UVISUSDRUGIMAGEDIR/csvupload/harvestrximages.log"
# The csv file that has been augmented with image data.
export UVISUSDRUGIMAGEDATAFILE="$UVISUSDRUGIMAGEDIR/csvupload/NDCImageDatabase.csv"
# The csv file with checkpointed image data.
export UVISUSDRUGIMAGECHECKPOINT="$UVISUSDRUGIMAGEDIR/csvupload/ImageCheckpoint.csv"
# The maxiumum number of RxImage requests per second
export UVISUSDRUGIMAGEMAXRATE="3"
# The URL of the RxImage API
export UVISUSDRUGIMAGEURL="http://rximage.nlm.nih.gov/api/rximage/1/rxbase"  
# The URL of the RxNorm RxCui lookup API (Json)
export UVISUSDRUGRXCUIURL="http://rxnav.nlm.nih.gov/REST/rxcui.json"  






