#!/bin/bash
# Define the UVIS Directory structure.
# This should be run once in each terminal session
# when working on UVIS software.
# This is run autmatically by the 'workenv UVIS' script  

# Absolute directories. 
# IMPORTANT - This script will need to be modified for each 
# development computer. 

source UVIS_LOCAL_ENV

# The following environment variables DO NOT need to be changed
# for different development environments if the relative UVIS directory
# structure is unchanged from that used by the software on GITHUB. 
 
# Define the environment variables for the US Drug application.

source UVIS_USDRUG

# Define the environment variables for the Sphinx application.

source UVIS_SPHINX

# Define the environment variables for the PharmCat web application.

source UVIS_PHARMCAT

# Define the environment variables for the UVIS Authentication server (Endponts).

source UVIS_AUTHENTICATE

